-- =============================================================================
-- _reset_pre_event.sql
-- Pre-event reset for AgreenTech 2026 Hack-Days (cohorte-mai-2026).
--
-- Run on 2026-05-12 23:00 (Casablanca time) to wipe all smoke test artifacts
-- generated by the swarm dry-run, while KEEPING:
--   - auth.users (the 11 porteurs + 2 mentors stay logged-in capable)
--   - public.profiles
--   - public.player_members (team membership)
--   - public.players (slug, name, idea preserved)
--   - public.events / cohorts / missions / deliverable_templates / levels
--
-- WIPES:
--   - public.submissions (cascades to evaluations via FK on delete cascade)
--   - public.evaluations (explicit delete, defensive — submissions cascade
--     would already do this, but we delete first for clarity in logs)
--   - public.pitch_scores
--   - players.score_project -> 0
--   - players.score_engagement -> 0
--   - players.current_level -> 'L0_diagnostic'
--   - players.onboarded_at -> NULL  (so /onboarding shows again on next login)
--
-- IDEMPOTENT: re-runnable. No-op if already wiped.
--
-- Apply via Supabase SQL editor (service_role) OR via psql against the prod
-- DB URL. Verify the wipe with the diagnostic SELECT block at the bottom.
--
-- ⚠️  DO NOT RUN ON 13/05 OR 14/05 — this destroys real participant data.
-- =============================================================================

begin;

-- 1. Wipe pitch_scores (jury day 2 scoring)
delete from public.pitch_scores;

-- 2. Wipe evaluations (mentor scores) — cascades from submissions but explicit here
delete from public.evaluations;

-- 3. Wipe submissions (this also cascades evaluations if any survived)
delete from public.submissions;

-- 4. Reset players to pristine pre-event state. The trg_player_onboarding
--    trigger (triggers.sql) has a guard that prevents clearing onboarded_at,
--    so we disable it for the duration of this reset and re-enable it after.
alter table public.players disable trigger trg_player_onboarding;

update public.players
   set score_project = 0,
       score_engagement = 0,
       current_level = 'L0_diagnostic'::public.level_id,
       onboarded_at = null;

alter table public.players enable trigger trg_player_onboarding;

-- 5. Drop announcements / live state if those tables exist (Phase 9 GameMaster).
do $$
begin
  if exists (select 1 from information_schema.tables where table_schema = 'public' and table_name = 'announcements') then
    execute 'delete from public.announcements';
  end if;
  if exists (select 1 from information_schema.tables where table_schema = 'public' and table_name = 'mentor_comments') then
    execute 'delete from public.mentor_comments';
  end if;
end $$;

-- 6. Clear results_published_at on the event (so /results stays gated until day 2)
update public.events
   set results_published_at = null
 where slug = 'hack-days-fes-meknes-mai-2026';

commit;

-- =============================================================================
-- Diagnostic — run after the transaction commits to confirm the wipe.
-- Expected counts: submissions=0, evaluations=0, pitch_scores=0,
-- players.score_project SUM = 0, players.onboarded_at all NULL.
-- =============================================================================

select 'submissions'         as table_name, count(*) as remaining from public.submissions
union all
select 'evaluations',                       count(*)              from public.evaluations
union all
select 'pitch_scores',                      count(*)              from public.pitch_scores
union all
select 'players.score_project_nonzero',     count(*)              from public.players where score_project <> 0
union all
select 'players.onboarded_at_set',          count(*)              from public.players where onboarded_at is not null
union all
select 'players.current_level_nonL0',       count(*)              from public.players where current_level <> 'L0_diagnostic'::public.level_id;
