insert into public.bootcamp_deliverables (
  id,
  day,
  start_time,
  end_time,
  duration,
  title,
  objective,
  expected_output,
  checkpoint,
  stage,
  kind,
  xp,
  is_active,
  is_required,
  game_master_note
) values
  ('bc-d1-intro-pitch', 'day_1', '15:30', '17:00', '01:30', 'Introduction et Ice-Breaker', 'Presentation du programme and 1 min pitch.', '1 min Pitch', 'make_it', 'L0_diagnostic', 'pitch', 40, true, true, 'Warm-up quest. Keep it fast and non-technical.'),
  ('bc-d1-market-study', 'day_1', '20:30', '21:00', '00:30', 'Session 1 - Etude de marche', 'Methodologie de l''etude de marche, cartographie marche, positionnement.', 'Cartographie Valeur/Prix', 'make_it', 'L1_problem', 'session', 60, true, true, 'Use this to force market framing before solution talk.'),
  ('bc-d1-market-map', 'day_1', '21:00', '22:00', '01:00', 'Atelier 1', 'Realiser sa cartographie marche.', 'Cartographie marche', 'make_it', 'L1_problem', 'atelier', 80, true, true, 'Deliverable can replace long market study decks.'),
  ('bc-d1-competition', 'day_1', '22:00', '22:30', '00:30', 'Session 2 - Analyse de la concurrence', 'Realiser sa grille comparative.', 'Grille comparative', 'make_it', 'L1_problem', 'session', 60, true, true, 'Short quest; deactivate if teams already have competitors mapped.'),
  ('bc-d2-compare-presentation', 'day_2', '10:30', '11:00', '00:30', 'Presentation grille comparative', 'Present comparative grid and receive coach corrections.', 'Grille comparative', 'make_it', 'L1_problem', 'presentation', 50, true, false, 'Good checkpoint for teams that rushed Day 1.'),
  ('bc-d2-persona', 'day_2', '11:00', '11:30', '00:30', 'Session 3 - Comprendre sa cible', 'Realiser son personae.', 'Fiche personae (1-2)', 'make_it', 'L1_problem', 'session', 70, true, true, 'Founder must name a real target, not a generic segment.'),
  ('bc-d2-environment', 'day_2', '12:30', '13:00', '00:30', 'Session 4 - Environnement', 'Comprendre environnement reglementaire/legal and identify opportunities/weaknesses.', 'SWOT et PESTEL', 'make_it', 'L1_problem', 'session', 70, true, true, 'Useful risk-control quest for regulated ideas.'),
  ('bc-d2-technical-feasibility', 'day_2', '13:30', '15:00', '01:30', 'Session 5 - Faisabilite technique + Atelier 5', 'Description produit/service, ressources techniques, plan de developpement.', 'Fiche produit avec plan de developpement, MoSCoW, plan d''implementation/marche', 'make_it', 'L2_solution', 'atelier', 150, true, true, 'Main Make it quest. Can be swapped with a demo-ready quest.'),
  ('bc-d2-financial-feasibility', 'day_2', '15:00', '16:30', '01:30', 'Session 6 - Faisabilite financiere + Atelier 6', 'Cout, depenses, seuil de rentabilite, ressources necessaires.', 'Fiche des depenses', 'sell_it', 'L2_solution', 'atelier', 120, true, true, 'Bridge toward selling by forcing cost and resource clarity.'),
  ('bc-d2-commercial-feasibility', 'day_2', '20:30', '21:00', '00:30', 'Session 6 - Faisabilite commerciale', 'Prix, canaux, strategie marketing.', 'Commercial feasibility note', 'sell_it', 'L3_traction', 'session', 90, true, true, 'Can be swapped with first-sale or waitlist quests for advanced teams.'),
  ('bc-d2-risk-mitigation', 'day_2', '21:00', '21:30', '00:30', 'Session 7 - Risques et mitigation', 'Comprendre les risques et mesures d''attenuation possible.', 'Matrice des risques', 'look_after_it', 'L3_traction', 'session', 90, true, true, 'Good Look after it entry point before committee.'),
  ('bc-d2-pitch', 'day_2', '21:30', '22:00', '00:30', 'Session 8 - Pitchs', 'Pitch practice before final jury.', 'Pitch draft', 'sell_it', 'L3_traction', 'pitch', 80, true, false, 'Practice quest, not the final committee artifact.'),
  ('bc-d3-remise-livrables', 'day_3', '10:00', '10:15', '00:15', 'Remise des livrables', 'Submit fiches depenses, Canva 4/7P, matrice des risques.', 'Complete deliverable pack', 'look_after_it', 'L4_committee', 'admin', 120, true, true, 'Locks the proof pack before final pitch.'),
  ('bc-d3-final-pitch', 'day_3', '10:30', '12:10', '01:40', 'Session Pitch finale', 'Final pitch and risk matrix defense.', 'Matrice de risques + final pitch', 'sell_it', 'L4_committee', 'pitch', 180, true, true, 'Final boss quest for bootcamp.'),
  ('bc-d3-deliberation', 'day_3', '12:10', '12:40', '00:30', 'Deliberation', 'Jury/coach decision and next-step assignment.', 'Decision and post-bootcamp next action', 'look_after_it', 'L4_committee', 'admin', 0, true, true, 'No founder XP; admin decision gate.')
on conflict (id) do update set
  day = excluded.day,
  start_time = excluded.start_time,
  end_time = excluded.end_time,
  duration = excluded.duration,
  title = excluded.title,
  objective = excluded.objective,
  expected_output = excluded.expected_output,
  checkpoint = excluded.checkpoint,
  stage = excluded.stage,
  kind = excluded.kind,
  xp = excluded.xp,
  is_active = excluded.is_active,
  is_required = excluded.is_required,
  game_master_note = excluded.game_master_note,
  updated_at = now();
